export const AUTHZ_ACTIONS = Object.freeze({
  // Analytics
  ANALYTICS_READ_BRANCH: "analytics.read.branch",
  ANALYTICS_READ_ASSIGNED: "analytics.read.assigned",
  ANALYTICS_READ_GLOBAL: "analytics.read.global",
  ANALYTICS_READ_PERSONAL: "analytics.read.personal",

  // Users
  USERS_READ_BRANCH: "users.read.branch",
  USERS_MANAGE_BRANCH: "users.manage.branch",
  USERS_MANAGE_GLOBAL: "users.manage.global",

  // Orders
  ORDERS_READ: "orders.read",
  ORDERS_WRITE: "orders.write",

  // Inventory
  INVENTORY_READ: "inventory.read",
  INVENTORY_WRITE: "inventory.write",

  // Products
  PRODUCT_READ: "product.read",
  PRODUCT_CREATE: "product.create",
  PRODUCT_UPDATE: "product.update",
  PRODUCT_DELETE: "product.delete",

  // Warehouse
  WAREHOUSE_READ: "warehouse.read",
  WAREHOUSE_WRITE: "warehouse.write",

  // Transfers
  TRANSFER_CREATE: "transfer.create",
  TRANSFER_APPROVE: "transfer.approve",
  TRANSFER_SHIP: "transfer.ship",
  TRANSFER_RECEIVE: "transfer.receive",
  TRANSFER_READ: "transfer.read",

  // Store management
  STORE_MANAGE: "store.manage",

  // Tasks
  TASK_READ: "task.read",
  TASK_UPDATE: "task.update",

  // Context
  CONTEXT_SWITCH_BRANCH: "context.switch.branch",
  CONTEXT_SIMULATE_BRANCH: "context.simulate.branch",
});

export const SYSTEM_ROLES = Object.freeze(["GLOBAL_ADMIN"]);

export const BRANCH_ROLES = Object.freeze([
  "BRANCH_ADMIN",
  "WAREHOUSE_MANAGER",
  "WAREHOUSE_STAFF",
  "PRODUCT_MANAGER",
  "ORDER_MANAGER",
  "POS_STAFF",
  "CASHIER",
  "ADMIN",
]);

export const TASK_ROLES = Object.freeze(["SHIPPER"]);

export const LEGACY_TO_BRANCH_ROLE = Object.freeze({
  ADMIN: "BRANCH_ADMIN",
  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER",
  WAREHOUSE_STAFF: "WAREHOUSE_STAFF",
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  ORDER_MANAGER: "ORDER_MANAGER",
  POS_STAFF: "POS_STAFF",
  CASHIER: "CASHIER",
});

export const ROLE_PERMISSIONS = Object.freeze({
  GLOBAL_ADMIN: ["*"],

  BRANCH_ADMIN: [
    AUTHZ_ACTIONS.ANALYTICS_READ_BRANCH,
    AUTHZ_ACTIONS.ANALYTICS_READ_ASSIGNED,
    AUTHZ_ACTIONS.USERS_READ_BRANCH,
    AUTHZ_ACTIONS.USERS_MANAGE_BRANCH,
    AUTHZ_ACTIONS.ORDERS_READ,
    AUTHZ_ACTIONS.ORDERS_WRITE,
    AUTHZ_ACTIONS.INVENTORY_READ,
    AUTHZ_ACTIONS.INVENTORY_WRITE,
    AUTHZ_ACTIONS.PRODUCT_READ,
    AUTHZ_ACTIONS.PRODUCT_CREATE,
    AUTHZ_ACTIONS.PRODUCT_UPDATE,
    AUTHZ_ACTIONS.PRODUCT_DELETE,
    AUTHZ_ACTIONS.WAREHOUSE_READ,
    AUTHZ_ACTIONS.WAREHOUSE_WRITE,
    AUTHZ_ACTIONS.TRANSFER_CREATE,
    AUTHZ_ACTIONS.TRANSFER_APPROVE,
    AUTHZ_ACTIONS.TRANSFER_SHIP,
    AUTHZ_ACTIONS.TRANSFER_RECEIVE,
    AUTHZ_ACTIONS.TRANSFER_READ,
    AUTHZ_ACTIONS.STORE_MANAGE,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],

  WAREHOUSE_MANAGER: [
    AUTHZ_ACTIONS.ANALYTICS_READ_BRANCH,
    AUTHZ_ACTIONS.INVENTORY_READ,
    AUTHZ_ACTIONS.INVENTORY_WRITE,
    AUTHZ_ACTIONS.PRODUCT_READ,
    AUTHZ_ACTIONS.WAREHOUSE_READ,
    AUTHZ_ACTIONS.WAREHOUSE_WRITE,
    AUTHZ_ACTIONS.TRANSFER_CREATE,
    AUTHZ_ACTIONS.TRANSFER_APPROVE,
    AUTHZ_ACTIONS.TRANSFER_SHIP,
    AUTHZ_ACTIONS.TRANSFER_RECEIVE,
    AUTHZ_ACTIONS.TRANSFER_READ,
    AUTHZ_ACTIONS.ORDERS_READ,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],

  WAREHOUSE_STAFF: [
    AUTHZ_ACTIONS.INVENTORY_READ,
    AUTHZ_ACTIONS.INVENTORY_WRITE,
    AUTHZ_ACTIONS.PRODUCT_READ,
    AUTHZ_ACTIONS.WAREHOUSE_READ,
    AUTHZ_ACTIONS.WAREHOUSE_WRITE,
    AUTHZ_ACTIONS.TRANSFER_CREATE,
    AUTHZ_ACTIONS.TRANSFER_SHIP,
    AUTHZ_ACTIONS.TRANSFER_RECEIVE,
    AUTHZ_ACTIONS.TRANSFER_READ,
    AUTHZ_ACTIONS.ORDERS_READ,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],

  PRODUCT_MANAGER: [
    AUTHZ_ACTIONS.PRODUCT_READ,
    AUTHZ_ACTIONS.PRODUCT_CREATE,
    AUTHZ_ACTIONS.PRODUCT_UPDATE,
    AUTHZ_ACTIONS.PRODUCT_DELETE,
    AUTHZ_ACTIONS.INVENTORY_READ,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],

  ORDER_MANAGER: [
    AUTHZ_ACTIONS.ANALYTICS_READ_BRANCH,
    AUTHZ_ACTIONS.ORDERS_READ,
    AUTHZ_ACTIONS.ORDERS_WRITE,
    AUTHZ_ACTIONS.TRANSFER_READ,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],

  POS_STAFF: [
    AUTHZ_ACTIONS.ORDERS_READ,
    AUTHZ_ACTIONS.ORDERS_WRITE,
    AUTHZ_ACTIONS.ANALYTICS_READ_PERSONAL,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],

  CASHIER: [
    AUTHZ_ACTIONS.ORDERS_READ,
    AUTHZ_ACTIONS.ORDERS_WRITE,
    AUTHZ_ACTIONS.ANALYTICS_READ_PERSONAL,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],

  SHIPPER: [
    AUTHZ_ACTIONS.TASK_READ,
    AUTHZ_ACTIONS.TASK_UPDATE,
    AUTHZ_ACTIONS.ANALYTICS_READ_PERSONAL,
  ],

  ADMIN: [
    AUTHZ_ACTIONS.ANALYTICS_READ_BRANCH,
    AUTHZ_ACTIONS.ANALYTICS_READ_ASSIGNED,
    AUTHZ_ACTIONS.USERS_READ_BRANCH,
    AUTHZ_ACTIONS.USERS_MANAGE_BRANCH,
    AUTHZ_ACTIONS.ORDERS_READ,
    AUTHZ_ACTIONS.ORDERS_WRITE,
    AUTHZ_ACTIONS.INVENTORY_READ,
    AUTHZ_ACTIONS.INVENTORY_WRITE,
    AUTHZ_ACTIONS.PRODUCT_READ,
    AUTHZ_ACTIONS.PRODUCT_CREATE,
    AUTHZ_ACTIONS.PRODUCT_UPDATE,
    AUTHZ_ACTIONS.PRODUCT_DELETE,
    AUTHZ_ACTIONS.WAREHOUSE_READ,
    AUTHZ_ACTIONS.WAREHOUSE_WRITE,
    AUTHZ_ACTIONS.TRANSFER_CREATE,
    AUTHZ_ACTIONS.TRANSFER_APPROVE,
    AUTHZ_ACTIONS.TRANSFER_SHIP,
    AUTHZ_ACTIONS.TRANSFER_RECEIVE,
    AUTHZ_ACTIONS.TRANSFER_READ,
    AUTHZ_ACTIONS.STORE_MANAGE,
    AUTHZ_ACTIONS.CONTEXT_SWITCH_BRANCH,
  ],
});

export const isSystemRole = (role) => SYSTEM_ROLES.includes(role);
export const isBranchRole = (role) => BRANCH_ROLES.includes(role);
export const isTaskRole = (role) => TASK_ROLES.includes(role);
