export const ORDER_AUDIT_ACTIONS = Object.freeze({
  CREATE_ORDER: "CREATE_ORDER",
  UPDATE_ORDER: "UPDATE_ORDER",
  UPDATE_STATUS: "UPDATE_STATUS",
  CANCEL_ORDER: "CANCEL_ORDER",
  COMPLETE_ORDER: "COMPLETE_ORDER",
  UPDATE_PAYMENT_STATUS: "UPDATE_PAYMENT_STATUS",
  ASSIGN_CARRIER: "ASSIGN_CARRIER",
  ASSIGN_BRANCH: "ASSIGN_BRANCH",
  CREATE_PAYMENT_LINK: "CREATE_PAYMENT_LINK",
  CREATE_SEPAY_QR: "CREATE_SEPAY_QR",
  PROCESS_VNPAY_IPN: "PROCESS_VNPAY_IPN",
  PROCESS_SEPAY_WEBHOOK: "PROCESS_SEPAY_WEBHOOK",
  PROCESS_CARRIER_WEBHOOK: "PROCESS_CARRIER_WEBHOOK",
  CREATE_POS_ORDER: "CREATE_POS_ORDER",
  PROCESS_POS_PAYMENT: "PROCESS_POS_PAYMENT",
  FINALIZE_POS_ORDER: "FINALIZE_POS_ORDER",
  ISSUE_POS_VAT_INVOICE: "ISSUE_POS_VAT_INVOICE",
  AUTO_CANCEL_EXPIRED_ORDER: "AUTO_CANCEL_EXPIRED_ORDER",
  ORDER_BASELINE: "ORDER_BASELINE",
});

export default ORDER_AUDIT_ACTIONS;
